// Copyright (c) Meta Platforms, Inc. and affiliates.
// All rights reserved.
//
// This source code is licensed under the BSD-style license found in the
// LICENSE file in the root directory of this source tree.

#pragma once

#include <hip/hip_runtime.h>
// rpp.h gates HIP APIs (e.g. rppSetStream) on RPP_BACKEND_HIP before any
// include defines it; rpp_backend.h is generated by RPP's CMake with the
// correct value. Include it first so declarations match our ROCm build.
#if __has_include(<rpp/rpp_backend.h>)
#include <rpp/rpp_backend.h>
#else
#ifndef RPP_BACKEND_HIP
#define RPP_BACKEND_HIP 1
#endif
#endif
#include <rpp/rpp.h>
#include <torch/types.h>

#include "FFMPEGCommon.h"
#include "Frame.h"

extern "C" {
#include <libavutil/pixdesc.h>
// Note: FFmpeg doesn't have native hwcontext_hip/rocm support
// Handle hardware acceleration using rocDecode
}

namespace facebook::torchcodec {

// PyTorch can handle up to 128 GPUs
constexpr int MAX_ROCM_GPUS = 128;

void initializeRocmContextWithPytorch(const torch::Device& device);

// ROCm context structure
struct RppContext {
  rppHandle_t handle;
  hipStream_t stream;
  unsigned int streamFlags;
};

// Custom deleter for RppContext
struct RppContextDeleter {
  void operator()(RppContext* ctx) const {
    if (ctx) {
      if (ctx->handle) {
        rppDestroy(ctx->handle, RPP_HIP_BACKEND);
      }
      if (ctx->stream) {
        hipError_t status = hipStreamDestroy(ctx->stream);
        TORCH_CHECK(
            status == hipSuccess,
            "hipStreamDestroy failed: ",
            hipGetErrorString(status));
        ctx->stream = nullptr;
      }
      delete ctx;
    }
  }
};

// Unique pointer type for RPP context
using UniqueRppContext = std::unique_ptr<RppContext, RppContextDeleter>;

// Chroma upsampling mode for NV12→RGB conversion.
enum class ChromaUpsampling {
  kNearestNeighbor, // rppt_yuv_to_rgb: matches FFmpeg 8-bit unscaled fast path
  kLinear,          // rppt_yuv_to_rgb_linear_v: best match for FFmpeg 10-bit
  kCubic,           // rppt_yuv_to_rgb_cubic_v: FFmpeg-compatible cubic
};

torch::Tensor convertNV12FrameToRGB(
    UniqueAVFrame& avFrame,
    const torch::Device& device,
    const UniqueRppContext& rppCtx,
    hipStream_t rodecStream,
    ChromaUpsampling chromaUpsampling,
    std::optional<torch::Tensor> preAllocatedOutputTensor = std::nullopt);

UniqueRppContext getRppStreamContext(const torch::Device& device);
void returnRppStreamContextToCache(
    const torch::Device& device,
    UniqueRppContext rppCtx);

void validatePreAllocatedTensorShape(
    const std::optional<torch::Tensor>& preAllocatedOutputTensor,
    const UniqueAVFrame& avFrame);

int getDeviceIndex(const torch::Device& device);

} // namespace facebook::torchcodec
